/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedJoinAcademyRouteImport } from './routes/_authenticated/join-academy'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOrganizerRouteImport } from './routes/_authenticated/organizer'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AcademiesIndexRouteImport } from './routes/academies.index'
import { Route as AcademiesSlugRouteImport } from './routes/academies.$slug'
import { Route as CCompetitionIdRouteImport } from './routes/c.$competitionId'
import { Route as ChamadaCompetitionIdRouteImport } from './routes/chamada.$competitionId'
import { Route as CheckInCodeRouteImport } from './routes/check-in.$code'
import { Route as CheckInScanRouteImport } from './routes/check-in.scan'
import { Route as DisplayMatchIdRouteImport } from './routes/display.$matchId'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as FFederationSlugRouteImport } from './routes/f.$federationSlug'
import { Route as MesaCompetitionIdRouteImport } from './routes/mesa.$competitionId'
import { Route as OSlugRouteImport } from './routes/o.$slug'
import { Route as PesagemCompetitionIdRouteImport } from './routes/pesagem.$competitionId'
import { Route as PodioCompetitionIdRouteImport } from './routes/podio.$competitionId'
import { Route as ScoreboardMatchIdRouteImport } from './routes/scoreboard.$matchId'
import { Route as TvCompetitionIdRouteImport } from './routes/tv.$competitionId'
import { Route as LangEventEventIdRouteImport } from './routes/$lang.event.$eventId'
import { Route as AuthenticatedASlugRouteImport } from './routes/_authenticated/a.$slug'
import { Route as AuthenticatedEventsCompetitionIdRouteImport } from './routes/_authenticated/events/$competitionId'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events/new'
import { Route as AuthenticatedOrganizerIndexRouteImport } from './routes/_authenticated/organizer/index'
import { Route as AuthenticatedOrganizerSlugRouteImport } from './routes/_authenticated/organizer/$slug'
import { Route as AuthenticatedOrganizerNewRouteImport } from './routes/_authenticated/organizer/new'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as MesaCompetitionIdIndexRouteImport } from './routes/mesa.$competitionId.index'
import { Route as MesaCompetitionIdMatRouteImport } from './routes/mesa.$competitionId.$mat'
import { Route as LangEventEventIdIndexRouteImport } from './routes/$lang.event.$eventId.index'
import { Route as LangEventEventIdRegisterRouteImport } from './routes/$lang.event.$eventId.register'
import { Route as AuthenticatedASlugIndexRouteImport } from './routes/_authenticated/a.$slug/index'
import { Route as AuthenticatedASlugAthletesRouteImport } from './routes/_authenticated/a.$slug/athletes'
import { Route as AuthenticatedASlugCompetitionsRouteImport } from './routes/_authenticated/a.$slug/competitions'
import { Route as DisplayMatCompetitionIdMatRouteImport } from './routes/display.mat.$competitionId.$mat'
import { Route as AuthenticatedASlugCompetitionsCompetitionIdRouteImport } from './routes/_authenticated/a.$slug/competitions.$competitionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinAcademyRoute =
  AuthenticatedJoinAcademyRouteImport.update({
    id: '/join-academy',
    path: '/join-academy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizerRoute = AuthenticatedOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AcademiesIndexRoute = AcademiesIndexRouteImport.update({
  id: '/academies/',
  path: '/academies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesSlugRoute = AcademiesSlugRouteImport.update({
  id: '/academies/$slug',
  path: '/academies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCompetitionIdRoute = CCompetitionIdRouteImport.update({
  id: '/c/$competitionId',
  path: '/c/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaCompetitionIdRoute = ChamadaCompetitionIdRouteImport.update({
  id: '/chamada/$competitionId',
  path: '/chamada/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInCodeRoute = CheckInCodeRouteImport.update({
  id: '/check-in/$code',
  path: '/check-in/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInScanRoute = CheckInScanRouteImport.update({
  id: '/check-in/scan',
  path: '/check-in/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayMatchIdRoute = DisplayMatchIdRouteImport.update({
  id: '/display/$matchId',
  path: '/display/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const FFederationSlugRoute = FFederationSlugRouteImport.update({
  id: '/f/$federationSlug',
  path: '/f/$federationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaCompetitionIdRoute = MesaCompetitionIdRouteImport.update({
  id: '/mesa/$competitionId',
  path: '/mesa/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PesagemCompetitionIdRoute = PesagemCompetitionIdRouteImport.update({
  id: '/pesagem/$competitionId',
  path: '/pesagem/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PodioCompetitionIdRoute = PodioCompetitionIdRouteImport.update({
  id: '/podio/$competitionId',
  path: '/podio/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardMatchIdRoute = ScoreboardMatchIdRouteImport.update({
  id: '/scoreboard/$matchId',
  path: '/scoreboard/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TvCompetitionIdRoute = TvCompetitionIdRouteImport.update({
  id: '/tv/$competitionId',
  path: '/tv/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangEventEventIdRoute = LangEventEventIdRouteImport.update({
  id: '/$lang/event/$eventId',
  path: '/$lang/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedASlugRoute = AuthenticatedASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsCompetitionIdRoute =
  AuthenticatedEventsCompetitionIdRouteImport.update({
    id: '/events/$competitionId',
    path: '/events/$competitionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizerIndexRoute =
  AuthenticatedOrganizerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizerRoute,
  } as any)
const AuthenticatedOrganizerSlugRoute =
  AuthenticatedOrganizerSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedOrganizerRoute,
  } as any)
const AuthenticatedOrganizerNewRoute =
  AuthenticatedOrganizerNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrganizerRoute,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaCompetitionIdIndexRoute = MesaCompetitionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MesaCompetitionIdRoute,
} as any)
const MesaCompetitionIdMatRoute = MesaCompetitionIdMatRouteImport.update({
  id: '/$mat',
  path: '/$mat',
  getParentRoute: () => MesaCompetitionIdRoute,
} as any)
const LangEventEventIdIndexRoute = LangEventEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangEventEventIdRoute,
} as any)
const LangEventEventIdRegisterRoute =
  LangEventEventIdRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => LangEventEventIdRoute,
  } as any)
const AuthenticatedASlugIndexRoute = AuthenticatedASlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedASlugRoute,
} as any)
const AuthenticatedASlugAthletesRoute =
  AuthenticatedASlugAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedASlugRoute,
  } as any)
const AuthenticatedASlugCompetitionsRoute =
  AuthenticatedASlugCompetitionsRouteImport.update({
    id: '/competitions',
    path: '/competitions',
    getParentRoute: () => AuthenticatedASlugRoute,
  } as any)
const DisplayMatCompetitionIdMatRoute =
  DisplayMatCompetitionIdMatRouteImport.update({
    id: '/display/mat/$competitionId/$mat',
    path: '/display/mat/$competitionId/$mat',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedASlugCompetitionsCompetitionIdRoute =
  AuthenticatedASlugCompetitionsCompetitionIdRouteImport.update({
    id: '/$competitionId',
    path: '/$competitionId',
    getParentRoute: () => AuthenticatedASlugCompetitionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/join-academy': typeof AuthenticatedJoinAcademyRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/organizer': typeof AuthenticatedOrganizerRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/c/$competitionId': typeof CCompetitionIdRoute
  '/chamada/$competitionId': typeof ChamadaCompetitionIdRoute
  '/check-in/$code': typeof CheckInCodeRoute
  '/check-in/scan': typeof CheckInScanRoute
  '/display/$matchId': typeof DisplayMatchIdRoute
  '/f/$federationSlug': typeof FFederationSlugRoute
  '/mesa/$competitionId': typeof MesaCompetitionIdRouteWithChildren
  '/o/$slug': typeof OSlugRoute
  '/pesagem/$competitionId': typeof PesagemCompetitionIdRoute
  '/podio/$competitionId': typeof PodioCompetitionIdRoute
  '/scoreboard/$matchId': typeof ScoreboardMatchIdRoute
  '/tv/$competitionId': typeof TvCompetitionIdRoute
  '/academies/': typeof AcademiesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/$lang/event/$eventId': typeof LangEventEventIdRouteWithChildren
  '/a/$slug': typeof AuthenticatedASlugRouteWithChildren
  '/events/$competitionId': typeof AuthenticatedEventsCompetitionIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/organizer/$slug': typeof AuthenticatedOrganizerSlugRoute
  '/organizer/new': typeof AuthenticatedOrganizerNewRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/mesa/$competitionId/$mat': typeof MesaCompetitionIdMatRoute
  '/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/mesa/$competitionId/': typeof MesaCompetitionIdIndexRoute
  '/$lang/event/$eventId/register': typeof LangEventEventIdRegisterRoute
  '/a/$slug/athletes': typeof AuthenticatedASlugAthletesRoute
  '/a/$slug/competitions': typeof AuthenticatedASlugCompetitionsRouteWithChildren
  '/display/mat/$competitionId/$mat': typeof DisplayMatCompetitionIdMatRoute
  '/$lang/event/$eventId/': typeof LangEventEventIdIndexRoute
  '/a/$slug/': typeof AuthenticatedASlugIndexRoute
  '/a/$slug/competitions/$competitionId': typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/join-academy': typeof AuthenticatedJoinAcademyRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/c/$competitionId': typeof CCompetitionIdRoute
  '/chamada/$competitionId': typeof ChamadaCompetitionIdRoute
  '/check-in/$code': typeof CheckInCodeRoute
  '/check-in/scan': typeof CheckInScanRoute
  '/display/$matchId': typeof DisplayMatchIdRoute
  '/f/$federationSlug': typeof FFederationSlugRoute
  '/o/$slug': typeof OSlugRoute
  '/pesagem/$competitionId': typeof PesagemCompetitionIdRoute
  '/podio/$competitionId': typeof PodioCompetitionIdRoute
  '/scoreboard/$matchId': typeof ScoreboardMatchIdRoute
  '/tv/$competitionId': typeof TvCompetitionIdRoute
  '/academies': typeof AcademiesIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/$competitionId': typeof AuthenticatedEventsCompetitionIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/organizer/$slug': typeof AuthenticatedOrganizerSlugRoute
  '/organizer/new': typeof AuthenticatedOrganizerNewRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/mesa/$competitionId/$mat': typeof MesaCompetitionIdMatRoute
  '/organizer': typeof AuthenticatedOrganizerIndexRoute
  '/mesa/$competitionId': typeof MesaCompetitionIdIndexRoute
  '/$lang/event/$eventId/register': typeof LangEventEventIdRegisterRoute
  '/a/$slug/athletes': typeof AuthenticatedASlugAthletesRoute
  '/a/$slug/competitions': typeof AuthenticatedASlugCompetitionsRouteWithChildren
  '/display/mat/$competitionId/$mat': typeof DisplayMatCompetitionIdMatRoute
  '/$lang/event/$eventId': typeof LangEventEventIdIndexRoute
  '/a/$slug': typeof AuthenticatedASlugIndexRoute
  '/a/$slug/competitions/$competitionId': typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/join-academy': typeof AuthenticatedJoinAcademyRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/organizer': typeof AuthenticatedOrganizerRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/c/$competitionId': typeof CCompetitionIdRoute
  '/chamada/$competitionId': typeof ChamadaCompetitionIdRoute
  '/check-in/$code': typeof CheckInCodeRoute
  '/check-in/scan': typeof CheckInScanRoute
  '/display/$matchId': typeof DisplayMatchIdRoute
  '/f/$federationSlug': typeof FFederationSlugRoute
  '/mesa/$competitionId': typeof MesaCompetitionIdRouteWithChildren
  '/o/$slug': typeof OSlugRoute
  '/pesagem/$competitionId': typeof PesagemCompetitionIdRoute
  '/podio/$competitionId': typeof PodioCompetitionIdRoute
  '/scoreboard/$matchId': typeof ScoreboardMatchIdRoute
  '/tv/$competitionId': typeof TvCompetitionIdRoute
  '/academies/': typeof AcademiesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/$lang/event/$eventId': typeof LangEventEventIdRouteWithChildren
  '/_authenticated/a/$slug': typeof AuthenticatedASlugRouteWithChildren
  '/_authenticated/events/$competitionId': typeof AuthenticatedEventsCompetitionIdRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/organizer/$slug': typeof AuthenticatedOrganizerSlugRoute
  '/_authenticated/organizer/new': typeof AuthenticatedOrganizerNewRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/mesa/$competitionId/$mat': typeof MesaCompetitionIdMatRoute
  '/_authenticated/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/mesa/$competitionId/': typeof MesaCompetitionIdIndexRoute
  '/$lang/event/$eventId/register': typeof LangEventEventIdRegisterRoute
  '/_authenticated/a/$slug/athletes': typeof AuthenticatedASlugAthletesRoute
  '/_authenticated/a/$slug/competitions': typeof AuthenticatedASlugCompetitionsRouteWithChildren
  '/display/mat/$competitionId/$mat': typeof DisplayMatCompetitionIdMatRoute
  '/$lang/event/$eventId/': typeof LangEventEventIdIndexRoute
  '/_authenticated/a/$slug/': typeof AuthenticatedASlugIndexRoute
  '/_authenticated/a/$slug/competitions/$competitionId': typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/join-academy'
    | '/membership'
    | '/onboarding'
    | '/organizer'
    | '/payments'
    | '/rankings'
    | '/academies/$slug'
    | '/c/$competitionId'
    | '/chamada/$competitionId'
    | '/check-in/$code'
    | '/check-in/scan'
    | '/display/$matchId'
    | '/f/$federationSlug'
    | '/mesa/$competitionId'
    | '/o/$slug'
    | '/pesagem/$competitionId'
    | '/podio/$competitionId'
    | '/scoreboard/$matchId'
    | '/tv/$competitionId'
    | '/academies/'
    | '/events/'
    | '/$lang/event/$eventId'
    | '/a/$slug'
    | '/events/$competitionId'
    | '/events/new'
    | '/organizer/$slug'
    | '/organizer/new'
    | '/api/webhooks/stripe'
    | '/mesa/$competitionId/$mat'
    | '/organizer/'
    | '/mesa/$competitionId/'
    | '/$lang/event/$eventId/register'
    | '/a/$slug/athletes'
    | '/a/$slug/competitions'
    | '/display/mat/$competitionId/$mat'
    | '/$lang/event/$eventId/'
    | '/a/$slug/'
    | '/a/$slug/competitions/$competitionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/join-academy'
    | '/membership'
    | '/onboarding'
    | '/payments'
    | '/rankings'
    | '/academies/$slug'
    | '/c/$competitionId'
    | '/chamada/$competitionId'
    | '/check-in/$code'
    | '/check-in/scan'
    | '/display/$matchId'
    | '/f/$federationSlug'
    | '/o/$slug'
    | '/pesagem/$competitionId'
    | '/podio/$competitionId'
    | '/scoreboard/$matchId'
    | '/tv/$competitionId'
    | '/academies'
    | '/events'
    | '/events/$competitionId'
    | '/events/new'
    | '/organizer/$slug'
    | '/organizer/new'
    | '/api/webhooks/stripe'
    | '/mesa/$competitionId/$mat'
    | '/organizer'
    | '/mesa/$competitionId'
    | '/$lang/event/$eventId/register'
    | '/a/$slug/athletes'
    | '/a/$slug/competitions'
    | '/display/mat/$competitionId/$mat'
    | '/$lang/event/$eventId'
    | '/a/$slug'
    | '/a/$slug/competitions/$competitionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/join-academy'
    | '/_authenticated/membership'
    | '/_authenticated/onboarding'
    | '/_authenticated/organizer'
    | '/_authenticated/payments'
    | '/_authenticated/rankings'
    | '/academies/$slug'
    | '/c/$competitionId'
    | '/chamada/$competitionId'
    | '/check-in/$code'
    | '/check-in/scan'
    | '/display/$matchId'
    | '/f/$federationSlug'
    | '/mesa/$competitionId'
    | '/o/$slug'
    | '/pesagem/$competitionId'
    | '/podio/$competitionId'
    | '/scoreboard/$matchId'
    | '/tv/$competitionId'
    | '/academies/'
    | '/events/'
    | '/$lang/event/$eventId'
    | '/_authenticated/a/$slug'
    | '/_authenticated/events/$competitionId'
    | '/_authenticated/events/new'
    | '/_authenticated/organizer/$slug'
    | '/_authenticated/organizer/new'
    | '/api/webhooks/stripe'
    | '/mesa/$competitionId/$mat'
    | '/_authenticated/organizer/'
    | '/mesa/$competitionId/'
    | '/$lang/event/$eventId/register'
    | '/_authenticated/a/$slug/athletes'
    | '/_authenticated/a/$slug/competitions'
    | '/display/mat/$competitionId/$mat'
    | '/$lang/event/$eventId/'
    | '/_authenticated/a/$slug/'
    | '/_authenticated/a/$slug/competitions/$competitionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  AcademiesSlugRoute: typeof AcademiesSlugRoute
  CCompetitionIdRoute: typeof CCompetitionIdRoute
  ChamadaCompetitionIdRoute: typeof ChamadaCompetitionIdRoute
  CheckInCodeRoute: typeof CheckInCodeRoute
  CheckInScanRoute: typeof CheckInScanRoute
  DisplayMatchIdRoute: typeof DisplayMatchIdRoute
  FFederationSlugRoute: typeof FFederationSlugRoute
  MesaCompetitionIdRoute: typeof MesaCompetitionIdRouteWithChildren
  OSlugRoute: typeof OSlugRoute
  PesagemCompetitionIdRoute: typeof PesagemCompetitionIdRoute
  PodioCompetitionIdRoute: typeof PodioCompetitionIdRoute
  ScoreboardMatchIdRoute: typeof ScoreboardMatchIdRoute
  TvCompetitionIdRoute: typeof TvCompetitionIdRoute
  AcademiesIndexRoute: typeof AcademiesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LangEventEventIdRoute: typeof LangEventEventIdRouteWithChildren
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  DisplayMatCompetitionIdMatRoute: typeof DisplayMatCompetitionIdMatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join-academy': {
      id: '/_authenticated/join-academy'
      path: '/join-academy'
      fullPath: '/join-academy'
      preLoaderRoute: typeof AuthenticatedJoinAcademyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizer': {
      id: '/_authenticated/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof AuthenticatedOrganizerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/academies/': {
      id: '/academies/'
      path: '/academies'
      fullPath: '/academies/'
      preLoaderRoute: typeof AcademiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies/$slug': {
      id: '/academies/$slug'
      path: '/academies/$slug'
      fullPath: '/academies/$slug'
      preLoaderRoute: typeof AcademiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$competitionId': {
      id: '/c/$competitionId'
      path: '/c/$competitionId'
      fullPath: '/c/$competitionId'
      preLoaderRoute: typeof CCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada/$competitionId': {
      id: '/chamada/$competitionId'
      path: '/chamada/$competitionId'
      fullPath: '/chamada/$competitionId'
      preLoaderRoute: typeof ChamadaCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/$code': {
      id: '/check-in/$code'
      path: '/check-in/$code'
      fullPath: '/check-in/$code'
      preLoaderRoute: typeof CheckInCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/scan': {
      id: '/check-in/scan'
      path: '/check-in/scan'
      fullPath: '/check-in/scan'
      preLoaderRoute: typeof CheckInScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$matchId': {
      id: '/display/$matchId'
      path: '/display/$matchId'
      fullPath: '/display/$matchId'
      preLoaderRoute: typeof DisplayMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$federationSlug': {
      id: '/f/$federationSlug'
      path: '/f/$federationSlug'
      fullPath: '/f/$federationSlug'
      preLoaderRoute: typeof FFederationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa/$competitionId': {
      id: '/mesa/$competitionId'
      path: '/mesa/$competitionId'
      fullPath: '/mesa/$competitionId'
      preLoaderRoute: typeof MesaCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesagem/$competitionId': {
      id: '/pesagem/$competitionId'
      path: '/pesagem/$competitionId'
      fullPath: '/pesagem/$competitionId'
      preLoaderRoute: typeof PesagemCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podio/$competitionId': {
      id: '/podio/$competitionId'
      path: '/podio/$competitionId'
      fullPath: '/podio/$competitionId'
      preLoaderRoute: typeof PodioCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard/$matchId': {
      id: '/scoreboard/$matchId'
      path: '/scoreboard/$matchId'
      fullPath: '/scoreboard/$matchId'
      preLoaderRoute: typeof ScoreboardMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$competitionId': {
      id: '/tv/$competitionId'
      path: '/tv/$competitionId'
      fullPath: '/tv/$competitionId'
      preLoaderRoute: typeof TvCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/event/$eventId': {
      id: '/$lang/event/$eventId'
      path: '/$lang/event/$eventId'
      fullPath: '/$lang/event/$eventId'
      preLoaderRoute: typeof LangEventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/a/$slug': {
      id: '/_authenticated/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof AuthenticatedASlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$competitionId': {
      id: '/_authenticated/events/$competitionId'
      path: '/events/$competitionId'
      fullPath: '/events/$competitionId'
      preLoaderRoute: typeof AuthenticatedEventsCompetitionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizer/': {
      id: '/_authenticated/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof AuthenticatedOrganizerIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizerRoute
    }
    '/_authenticated/organizer/$slug': {
      id: '/_authenticated/organizer/$slug'
      path: '/$slug'
      fullPath: '/organizer/$slug'
      preLoaderRoute: typeof AuthenticatedOrganizerSlugRouteImport
      parentRoute: typeof AuthenticatedOrganizerRoute
    }
    '/_authenticated/organizer/new': {
      id: '/_authenticated/organizer/new'
      path: '/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof AuthenticatedOrganizerNewRouteImport
      parentRoute: typeof AuthenticatedOrganizerRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa/$competitionId/': {
      id: '/mesa/$competitionId/'
      path: '/'
      fullPath: '/mesa/$competitionId/'
      preLoaderRoute: typeof MesaCompetitionIdIndexRouteImport
      parentRoute: typeof MesaCompetitionIdRoute
    }
    '/mesa/$competitionId/$mat': {
      id: '/mesa/$competitionId/$mat'
      path: '/$mat'
      fullPath: '/mesa/$competitionId/$mat'
      preLoaderRoute: typeof MesaCompetitionIdMatRouteImport
      parentRoute: typeof MesaCompetitionIdRoute
    }
    '/$lang/event/$eventId/': {
      id: '/$lang/event/$eventId/'
      path: '/'
      fullPath: '/$lang/event/$eventId/'
      preLoaderRoute: typeof LangEventEventIdIndexRouteImport
      parentRoute: typeof LangEventEventIdRoute
    }
    '/$lang/event/$eventId/register': {
      id: '/$lang/event/$eventId/register'
      path: '/register'
      fullPath: '/$lang/event/$eventId/register'
      preLoaderRoute: typeof LangEventEventIdRegisterRouteImport
      parentRoute: typeof LangEventEventIdRoute
    }
    '/_authenticated/a/$slug/': {
      id: '/_authenticated/a/$slug/'
      path: '/'
      fullPath: '/a/$slug/'
      preLoaderRoute: typeof AuthenticatedASlugIndexRouteImport
      parentRoute: typeof AuthenticatedASlugRoute
    }
    '/_authenticated/a/$slug/athletes': {
      id: '/_authenticated/a/$slug/athletes'
      path: '/athletes'
      fullPath: '/a/$slug/athletes'
      preLoaderRoute: typeof AuthenticatedASlugAthletesRouteImport
      parentRoute: typeof AuthenticatedASlugRoute
    }
    '/_authenticated/a/$slug/competitions': {
      id: '/_authenticated/a/$slug/competitions'
      path: '/competitions'
      fullPath: '/a/$slug/competitions'
      preLoaderRoute: typeof AuthenticatedASlugCompetitionsRouteImport
      parentRoute: typeof AuthenticatedASlugRoute
    }
    '/display/mat/$competitionId/$mat': {
      id: '/display/mat/$competitionId/$mat'
      path: '/display/mat/$competitionId/$mat'
      fullPath: '/display/mat/$competitionId/$mat'
      preLoaderRoute: typeof DisplayMatCompetitionIdMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/a/$slug/competitions/$competitionId': {
      id: '/_authenticated/a/$slug/competitions/$competitionId'
      path: '/$competitionId'
      fullPath: '/a/$slug/competitions/$competitionId'
      preLoaderRoute: typeof AuthenticatedASlugCompetitionsCompetitionIdRouteImport
      parentRoute: typeof AuthenticatedASlugCompetitionsRoute
    }
  }
}

interface AuthenticatedOrganizerRouteChildren {
  AuthenticatedOrganizerSlugRoute: typeof AuthenticatedOrganizerSlugRoute
  AuthenticatedOrganizerNewRoute: typeof AuthenticatedOrganizerNewRoute
  AuthenticatedOrganizerIndexRoute: typeof AuthenticatedOrganizerIndexRoute
}

const AuthenticatedOrganizerRouteChildren: AuthenticatedOrganizerRouteChildren =
  {
    AuthenticatedOrganizerSlugRoute: AuthenticatedOrganizerSlugRoute,
    AuthenticatedOrganizerNewRoute: AuthenticatedOrganizerNewRoute,
    AuthenticatedOrganizerIndexRoute: AuthenticatedOrganizerIndexRoute,
  }

const AuthenticatedOrganizerRouteWithChildren =
  AuthenticatedOrganizerRoute._addFileChildren(
    AuthenticatedOrganizerRouteChildren,
  )

interface AuthenticatedASlugCompetitionsRouteChildren {
  AuthenticatedASlugCompetitionsCompetitionIdRoute: typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}

const AuthenticatedASlugCompetitionsRouteChildren: AuthenticatedASlugCompetitionsRouteChildren =
  {
    AuthenticatedASlugCompetitionsCompetitionIdRoute:
      AuthenticatedASlugCompetitionsCompetitionIdRoute,
  }

const AuthenticatedASlugCompetitionsRouteWithChildren =
  AuthenticatedASlugCompetitionsRoute._addFileChildren(
    AuthenticatedASlugCompetitionsRouteChildren,
  )

interface AuthenticatedASlugRouteChildren {
  AuthenticatedASlugAthletesRoute: typeof AuthenticatedASlugAthletesRoute
  AuthenticatedASlugCompetitionsRoute: typeof AuthenticatedASlugCompetitionsRouteWithChildren
  AuthenticatedASlugIndexRoute: typeof AuthenticatedASlugIndexRoute
}

const AuthenticatedASlugRouteChildren: AuthenticatedASlugRouteChildren = {
  AuthenticatedASlugAthletesRoute: AuthenticatedASlugAthletesRoute,
  AuthenticatedASlugCompetitionsRoute:
    AuthenticatedASlugCompetitionsRouteWithChildren,
  AuthenticatedASlugIndexRoute: AuthenticatedASlugIndexRoute,
}

const AuthenticatedASlugRouteWithChildren =
  AuthenticatedASlugRoute._addFileChildren(AuthenticatedASlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJoinAcademyRoute: typeof AuthenticatedJoinAcademyRoute
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrganizerRoute: typeof AuthenticatedOrganizerRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedASlugRoute: typeof AuthenticatedASlugRouteWithChildren
  AuthenticatedEventsCompetitionIdRoute: typeof AuthenticatedEventsCompetitionIdRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJoinAcademyRoute: AuthenticatedJoinAcademyRoute,
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrganizerRoute: AuthenticatedOrganizerRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedASlugRoute: AuthenticatedASlugRouteWithChildren,
  AuthenticatedEventsCompetitionIdRoute: AuthenticatedEventsCompetitionIdRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MesaCompetitionIdRouteChildren {
  MesaCompetitionIdMatRoute: typeof MesaCompetitionIdMatRoute
  MesaCompetitionIdIndexRoute: typeof MesaCompetitionIdIndexRoute
}

const MesaCompetitionIdRouteChildren: MesaCompetitionIdRouteChildren = {
  MesaCompetitionIdMatRoute: MesaCompetitionIdMatRoute,
  MesaCompetitionIdIndexRoute: MesaCompetitionIdIndexRoute,
}

const MesaCompetitionIdRouteWithChildren =
  MesaCompetitionIdRoute._addFileChildren(MesaCompetitionIdRouteChildren)

interface LangEventEventIdRouteChildren {
  LangEventEventIdRegisterRoute: typeof LangEventEventIdRegisterRoute
  LangEventEventIdIndexRoute: typeof LangEventEventIdIndexRoute
}

const LangEventEventIdRouteChildren: LangEventEventIdRouteChildren = {
  LangEventEventIdRegisterRoute: LangEventEventIdRegisterRoute,
  LangEventEventIdIndexRoute: LangEventEventIdIndexRoute,
}

const LangEventEventIdRouteWithChildren =
  LangEventEventIdRoute._addFileChildren(LangEventEventIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  AcademiesSlugRoute: AcademiesSlugRoute,
  CCompetitionIdRoute: CCompetitionIdRoute,
  ChamadaCompetitionIdRoute: ChamadaCompetitionIdRoute,
  CheckInCodeRoute: CheckInCodeRoute,
  CheckInScanRoute: CheckInScanRoute,
  DisplayMatchIdRoute: DisplayMatchIdRoute,
  FFederationSlugRoute: FFederationSlugRoute,
  MesaCompetitionIdRoute: MesaCompetitionIdRouteWithChildren,
  OSlugRoute: OSlugRoute,
  PesagemCompetitionIdRoute: PesagemCompetitionIdRoute,
  PodioCompetitionIdRoute: PodioCompetitionIdRoute,
  ScoreboardMatchIdRoute: ScoreboardMatchIdRoute,
  TvCompetitionIdRoute: TvCompetitionIdRoute,
  AcademiesIndexRoute: AcademiesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LangEventEventIdRoute: LangEventEventIdRouteWithChildren,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  DisplayMatCompetitionIdMatRoute: DisplayMatCompetitionIdMatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
