/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as CCompetitionIdRouteImport } from './routes/c.$competitionId'
import { Route as AuthenticatedASlugRouteImport } from './routes/_authenticated/a.$slug'
import { Route as AuthenticatedASlugIndexRouteImport } from './routes/_authenticated/a.$slug/index'
import { Route as AuthenticatedASlugAthletesRouteImport } from './routes/_authenticated/a.$slug/athletes'
import { Route as AuthenticatedASlugCompetitionsRouteImport } from './routes/_authenticated/a.$slug/competitions'
import { Route as AuthenticatedASlugCompetitionsCompetitionIdRouteImport } from './routes/_authenticated/a.$slug/competitions.$competitionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CCompetitionIdRoute = CCompetitionIdRouteImport.update({
  id: '/c/$competitionId',
  path: '/c/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedASlugRoute = AuthenticatedASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedASlugIndexRoute = AuthenticatedASlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedASlugRoute,
} as any)
const AuthenticatedASlugAthletesRoute =
  AuthenticatedASlugAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedASlugRoute,
  } as any)
const AuthenticatedASlugCompetitionsRoute =
  AuthenticatedASlugCompetitionsRouteImport.update({
    id: '/competitions',
    path: '/competitions',
    getParentRoute: () => AuthenticatedASlugRoute,
  } as any)
const AuthenticatedASlugCompetitionsCompetitionIdRoute =
  AuthenticatedASlugCompetitionsCompetitionIdRouteImport.update({
    id: '/$competitionId',
    path: '/$competitionId',
    getParentRoute: () => AuthenticatedASlugCompetitionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/c/$competitionId': typeof CCompetitionIdRoute
  '/a/$slug': typeof AuthenticatedASlugRouteWithChildren
  '/a/$slug/athletes': typeof AuthenticatedASlugAthletesRoute
  '/a/$slug/competitions': typeof AuthenticatedASlugCompetitionsRouteWithChildren
  '/a/$slug/': typeof AuthenticatedASlugIndexRoute
  '/a/$slug/competitions/$competitionId': typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/c/$competitionId': typeof CCompetitionIdRoute
  '/a/$slug/athletes': typeof AuthenticatedASlugAthletesRoute
  '/a/$slug/competitions': typeof AuthenticatedASlugCompetitionsRouteWithChildren
  '/a/$slug': typeof AuthenticatedASlugIndexRoute
  '/a/$slug/competitions/$competitionId': typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/c/$competitionId': typeof CCompetitionIdRoute
  '/_authenticated/a/$slug': typeof AuthenticatedASlugRouteWithChildren
  '/_authenticated/a/$slug/athletes': typeof AuthenticatedASlugAthletesRoute
  '/_authenticated/a/$slug/competitions': typeof AuthenticatedASlugCompetitionsRouteWithChildren
  '/_authenticated/a/$slug/': typeof AuthenticatedASlugIndexRoute
  '/_authenticated/a/$slug/competitions/$competitionId': typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/c/$competitionId'
    | '/a/$slug'
    | '/a/$slug/athletes'
    | '/a/$slug/competitions'
    | '/a/$slug/'
    | '/a/$slug/competitions/$competitionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/c/$competitionId'
    | '/a/$slug/athletes'
    | '/a/$slug/competitions'
    | '/a/$slug'
    | '/a/$slug/competitions/$competitionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/onboarding'
    | '/c/$competitionId'
    | '/_authenticated/a/$slug'
    | '/_authenticated/a/$slug/athletes'
    | '/_authenticated/a/$slug/competitions'
    | '/_authenticated/a/$slug/'
    | '/_authenticated/a/$slug/competitions/$competitionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CCompetitionIdRoute: typeof CCompetitionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/c/$competitionId': {
      id: '/c/$competitionId'
      path: '/c/$competitionId'
      fullPath: '/c/$competitionId'
      preLoaderRoute: typeof CCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/a/$slug': {
      id: '/_authenticated/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof AuthenticatedASlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/a/$slug/': {
      id: '/_authenticated/a/$slug/'
      path: '/'
      fullPath: '/a/$slug/'
      preLoaderRoute: typeof AuthenticatedASlugIndexRouteImport
      parentRoute: typeof AuthenticatedASlugRoute
    }
    '/_authenticated/a/$slug/athletes': {
      id: '/_authenticated/a/$slug/athletes'
      path: '/athletes'
      fullPath: '/a/$slug/athletes'
      preLoaderRoute: typeof AuthenticatedASlugAthletesRouteImport
      parentRoute: typeof AuthenticatedASlugRoute
    }
    '/_authenticated/a/$slug/competitions': {
      id: '/_authenticated/a/$slug/competitions'
      path: '/competitions'
      fullPath: '/a/$slug/competitions'
      preLoaderRoute: typeof AuthenticatedASlugCompetitionsRouteImport
      parentRoute: typeof AuthenticatedASlugRoute
    }
    '/_authenticated/a/$slug/competitions/$competitionId': {
      id: '/_authenticated/a/$slug/competitions/$competitionId'
      path: '/$competitionId'
      fullPath: '/a/$slug/competitions/$competitionId'
      preLoaderRoute: typeof AuthenticatedASlugCompetitionsCompetitionIdRouteImport
      parentRoute: typeof AuthenticatedASlugCompetitionsRoute
    }
  }
}

interface AuthenticatedASlugCompetitionsRouteChildren {
  AuthenticatedASlugCompetitionsCompetitionIdRoute: typeof AuthenticatedASlugCompetitionsCompetitionIdRoute
}

const AuthenticatedASlugCompetitionsRouteChildren: AuthenticatedASlugCompetitionsRouteChildren =
  {
    AuthenticatedASlugCompetitionsCompetitionIdRoute:
      AuthenticatedASlugCompetitionsCompetitionIdRoute,
  }

const AuthenticatedASlugCompetitionsRouteWithChildren =
  AuthenticatedASlugCompetitionsRoute._addFileChildren(
    AuthenticatedASlugCompetitionsRouteChildren,
  )

interface AuthenticatedASlugRouteChildren {
  AuthenticatedASlugAthletesRoute: typeof AuthenticatedASlugAthletesRoute
  AuthenticatedASlugCompetitionsRoute: typeof AuthenticatedASlugCompetitionsRouteWithChildren
  AuthenticatedASlugIndexRoute: typeof AuthenticatedASlugIndexRoute
}

const AuthenticatedASlugRouteChildren: AuthenticatedASlugRouteChildren = {
  AuthenticatedASlugAthletesRoute: AuthenticatedASlugAthletesRoute,
  AuthenticatedASlugCompetitionsRoute:
    AuthenticatedASlugCompetitionsRouteWithChildren,
  AuthenticatedASlugIndexRoute: AuthenticatedASlugIndexRoute,
}

const AuthenticatedASlugRouteWithChildren =
  AuthenticatedASlugRoute._addFileChildren(AuthenticatedASlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedASlugRoute: typeof AuthenticatedASlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedASlugRoute: AuthenticatedASlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CCompetitionIdRoute: CCompetitionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
